version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: monthly
      day: 1
      time: "06:00"
      timezone: Europe/Oslo
    open-pull-requests-limit: 5
    groups:
      gradle-minor-and-patch:
        update-types:
          - minor
          - patch
