package no.beint.vev.pg;

/**
 * Declared PostgreSQL 18 check constraint. The expression is schema metadata, never executable SQL in Vev.
 *
 * @param name explicit constraint name
 * @param expression exact {@code pg_get_expr(conbin, conrelid, false)} output for ordinary checks;
 *                   canonical quoted-column expression for a generated binary bound
 * @param binaryColumn bounded binary column, or empty for an ordinary exact expression
 * @param maximumBytes binary byte bound, or zero for an ordinary exact expression
 */
public record PgCheck(String name, String expression, String binaryColumn, int maximumBytes) {
    /** Maximum number of declared checks on one entity. */
    public static final int MAXIMUM_PER_ENTITY = 32;
    /** Maximum characters in one deparsed expression. */
    public static final int MAXIMUM_EXPRESSION_LENGTH = 4096;
    /** Maximum total expression characters retained by one closed model. */
    public static final int MAXIMUM_MODEL_CHARACTERS = 16 * 1024 * 1024;

    /**
     * Captures an ordinary check's exact PostgreSQL deparsed definition.
     *
     * @param name explicit database constraint name
     * @param expression exact deparsed definition
     */
    public PgCheck(String name, String expression) {
        this(name, expression, "", 0);
    }

    /**
     * Creates the required generated byte-length constraint for one binary column.
     *
     * @param name explicit migration-installed constraint name
     * @param column exact binary column identifier
     * @param maximumBytes maximum stored byte count
     * @return bound metadata whose identifier quoting is verified with PostgreSQL's own formatter
     */
    public static PgCheck binaryMaximum(String name, String column, int maximumBytes) {
        return new PgCheck(name, binaryExpression(column, maximumBytes), column, maximumBytes);
    }

    /**
     * Captures bounded, exact schema metadata.
     *
     * @param name safe unquoted identifier
     * @param expression exact deparsed ordinary expression, or the canonical generated binary expression
     * @param binaryColumn bounded binary column, or empty for an ordinary expression
     * @param maximumBytes binary byte bound, or zero for an ordinary expression
     */
    public PgCheck {
        if (name == null || !name.matches("[a-z][a-z0-9_]{0,62}")) {
            throw new IllegalArgumentException("Unsafe generated PostgreSQL check-constraint identifier");
        }
        if (expression == null || expression.isBlank() || expression.length() > MAXIMUM_EXPRESSION_LENGTH
                || expression.indexOf('\0') >= 0 || !wellFormedUnicode(expression)) {
            throw new IllegalArgumentException("Check expression must be bounded, nonempty Unicode schema metadata");
        }
        if (binaryColumn == null || (binaryColumn.isEmpty() ? maximumBytes != 0
                : !binaryColumn.matches("[a-z][a-z0-9_]{0,62}") || maximumBytes < 1
                    || maximumBytes > no.beint.vev.Binary.MAXIMUM_LENGTH
                    || !expression.equals(binaryExpression(binaryColumn, maximumBytes)))) {
            throw new IllegalArgumentException("Binary check must declare one exact bounded column expression");
        }
    }

    private static String binaryExpression(String column, int maximumBytes) {
        return "(octet_length(\"" + column + "\") <= " + maximumBytes + ')';
    }

    private static boolean wellFormedUnicode(String value) {
        for (int index = 0; index < value.length(); index++) {
            char character = value.charAt(index);
            if (Character.isHighSurrogate(character)) {
                if (++index == value.length() || !Character.isLowSurrogate(value.charAt(index))) return false;
            } else if (Character.isLowSurrogate(character)) return false;
        }
        return true;
    }
}
