package no.beint.vev.compiler;

import java.util.List;
import java.util.Map;
import java.util.Locale;

final class KotlinWriter {
    private KotlinWriter() {}

    static String write(String packageName, String className, List<QueryCompiler.Query> queries, Map<String, PgType> domains) {
        StringBuilder out = new StringBuilder("// Generated by Vev 1.0.0. Edit the SQL source, not this file.\npackage ");
        out.append(java.util.Arrays.stream(packageName.split("\\.")).map(KotlinWriter::id).collect(java.util.stream.Collectors.joining("."))).append("\n\n");
        domains.forEach((name, type) -> out.append("@JvmInline\nvalue class ").append(id(name)).append("(val value: ").append(type.kotlin()).append(")\n\n"));
        for (var query : queries) {
            if (query.columns().isEmpty()) continue;
            out.append("data class ").append(id(rowName(query.source().name()))).append("(\n");
            for (var column : query.columns()) out.append("    val ").append(id(camel(column.name()))).append(": ").append(column.kotlin()).append(",\n");
            out.append(")\n\n");
        }
        out.append("object ").append(id(className)).append(" {\n");
        for (var query : queries) {
            var source = query.source();
            String row = id(rowName(source.name()));
            String result = switch (source.cardinality()) { case "many" -> "List<" + row + ">"; case "optional" -> row + "?"; case "one" -> row; default -> "Long"; };
            out.append("    fun ").append(id(source.name())).append(source.tenant() == null ? "(session: no.beint.vev.Session" : "(session: no.beint.vev.TenantSession");
            for (var parameter : query.parameters()) if (!parameter.name().equals(source.tenant())) out.append(", ").append(id(parameter.name())).append(": ").append(parameter.kotlin());
            out.append("): ").append(result).append(source.tenant() == null ? " =\n        session." : " =\n        session.session().").append(switch (source.cardinality()) { case "many" -> "list"; case "exec" -> "execute"; default -> source.cardinality(); }).append("(\n            ").append(quote(source.sql())).append(",\n");
            if (source.cardinality().equals("many")) out.append("            ").append(source.maxRows()).append(",\n");
            out.append(source.parameters().isEmpty() ? "            { _ ->\n" : "            { _vevBindings ->\n");
            for (int i = 0; i < source.parameters().size(); i++) {
                String name = source.parameters().get(i);
                var parameter = query.parameters().stream().filter(p -> p.name().equals(name)).findFirst().orElseThrow();
                String value = name.equals(source.tenant()) ? "session.tenantId()" : id(name);
                if (parameter.domain() != null) value += parameter.nullable() ? "?.value" : ".value";
                if (parameter.type().element() != null) {
                    out.append("                _vevBindings.array(").append(i + 1).append(", ").append(quote(parameter.type().element().postgres())).append(", ").append(value).append(parameter.nullable() ? "?.toTypedArray()" : ".toTypedArray()").append(")\n");
                } else {
                    out.append("                _vevBindings.statement().setObject(").append(i + 1).append(", ").append(value).append(", ").append(parameter.type().jdbc()).append(")\n");
                }
            }
            out.append("            }");
            if (!query.columns().isEmpty()) {
                out.append(",\n            { _vevResult ->\n                ").append(row).append("(\n");
                for (int i = 0; i < query.columns().size(); i++) {
                    var column = query.columns().get(i);
                    String read = read(column.type(), i + 1);
                    if (!column.nullable()) read = "requireNotNull(" + read + ") { " + quote(source.name() + ": unexpected NULL for " + column.name()) + " }";
                    if (column.domain() != null) read = column.nullable() ? read + "?.let { " + id(column.domain()) + "(it) }" : id(column.domain()) + "(" + read + ")";
                    out.append("                    ").append(read).append(",\n");
                }
                out.append("                )\n            }");
            }
            out.append("\n        )\n\n");
        }
        return out.append("}\n").toString();
    }

    private static String read(PgType type, int index) {
        if (type.element() != null) return "no.beint.vev.Values.array(_vevResult, " + index + ", " + javaClass(type.element()) + ")";
        if (type.postgres().equals("json") || type.postgres().equals("jsonb")) return "_vevResult.getString(" + index + ")";
        if (type.postgres().equals("bytea")) return "_vevResult.getBytes(" + index + ")";
        return "_vevResult.getObject(" + index + ", " + javaClass(type) + ")";
    }

    private static String javaClass(PgType type) {
        return switch (type.kotlin()) {
            case "Boolean", "Short", "Int", "Long", "Float", "Double" -> type.kotlin() + "::class.javaObjectType";
            default -> type.kotlin() + "::class.java";
        };
    }

    static String rowName(String method) { String name = camel(method); return name.substring(0, 1).toUpperCase(Locale.ROOT) + name.substring(1) + "Row"; }
    static String camel(String name) {
        StringBuilder result = new StringBuilder();
        boolean upper = false;
        for (char c : name.toCharArray()) { if (c == '_') upper = true; else { result.append(upper ? Character.toUpperCase(c) : c); upper = false; } }
        return result.toString();
    }
    private static String id(String name) { return "`" + name + "`"; }
    private static String quote(String text) { return "\"" + text.replace("\\", "\\\\").replace("\"", "\\\"").replace("$", "\\$").replace("\n", "\\n").replace("\r", "\\r").replace("\t", "\\t") + "\""; }
}
